spring:
  application:
    name: accountapi
  profiles:
    active:
      "default"

server:
  port: 9090
account:
  accountno: 12345
  type: saving-default
  accountinfo:
    name: pit-default
    email: default@123
  onCallSupport:
    -(91)1234567890
    -(91)0987654321